version: "3.7"
services:

  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    networks:
      envoymesh:
        aliases:
          - redis_server
    expose:
      - "6379"
    # for debuging
    # ports:
    #   - "6379:6379"
  
  redis_test:
    build:
      context: .
      dockerfile: Dockerfile-redis
    networks:
      envoymesh:
        aliases:
          - redis_test-server
    expose:
      - "6379"
    # for debuging
    # ports:
    #   - "6378:6379"

  server-proxy:
    build:
      context: .
      dockerfile: Dockerfile-backenvoy
    volumes:
      - ./redis-envoy.yaml:/etc/envoy.yaml
    networks:
      envoymesh:
        aliases:
          - server-proxy
    expose:
      - "1999"
      - "8002"
    # for debuging  
    # ports:
      # - "1999:1999"
      # - "8002:8002"
  
  frontend-client:
    build:
      context: .
      dockerfile: Dockerfile-client
    networks:
      envoymesh:
        aliases:
          - frontend-client

networks:
  envoymesh: {}
